### ISSUE TITLE
Pushing people not working, had to monkey patch API_KEY into query_values

### ISSUE THREAD

**Issue by lukerohde** [3dna/nationbuilder-rb#4]
I'm attempting to push people and was getting unhelpful non-JSON response type errors.  Stepping into your code I found the server was returning 400 bad request.  I noticed the API Explorer was working with my JSON person and the API Explorer's URL contained the access_token.  I monkey patched Client.call to include the access_token like so request_args[:query][:access_token] = @api_key.  That fixed it.  Doesn't seem to like the access_token in the request body?  Thoughts?  I'm not using the full OAUTH but rather the a test token.

**Comment by aq1018** [comment]
@lukerohde Yes, the access token should not be inside the requests body. According to OAuth 2 specs. It should be either inside `Authentication` header or inside query string.
